In [ ]:
#import necessary libraries
import numpy as np 
import pandas as pd

In [ ]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_50e26035afd94f35b04c55fa79b2ad2f = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='EURISDKdDxFSP-X95BuFXYWrY1G-SY43l5Ukygt6ai6X',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

body = client_50e26035afd94f35b04c55fa79b2ad2f.get_object(Bucket='demoday4-donotdelete-pr-gyz9iesk0tfedz',Key='loan_prediction.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(heart)
df.head()


ModuleNotFoundError: ignored

In [ ]:
df = pd.read_csv("Heart.csv")
df.head()

AVGHEARTBEATSPERMIN  PALPITATIONSPERDAY  CHOLESTEROL  BMI HEARTFAILURE  \
0                   93                  22          163   25            N   
1                  108                  22          181   24            N   
2                   86                   0          239   20            N   
3                   80                  36          164   31            Y   
4                   66                  36          185   23            N   

   AGE SEX FAMILYHISTORY SMOKERLAST5YRS  EXERCISEMINPERWEEK  
0   49   F             N              N                 110  
1   32   F             N              N                 192  
2   60   F             N              N                 121  
3   45   F             Y              N                 141  
4   39   F             N              N                  63

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10800 entries, 0 to 10799
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   AVGHEARTBEATSPERMIN  10800 non-null  int64 
 1   PALPITATIONSPERDAY   10800 non-null  int64 
 2   CHOLESTEROL          10800 non-null  int64 
 3   BMI                  10800 non-null  int64 
 4   HEARTFAILURE         10800 non-null  object
 5   AGE                  10800 non-null  int64 
 6   SEX                  10800 non-null  object
 7   FAMILYHISTORY        10800 non-null  object
 8   SMOKERLAST5YRS       10800 non-null  object
 9   EXERCISEMINPERWEEK   10800 non-null  int64 
dtypes: int64(6), object(4)
memory usage: 843.9+ KB


In [ ]:
#decsriptive analysis
df.describe()

AVGHEARTBEATSPERMIN  PALPITATIONSPERDAY   CHOLESTEROL           BMI  \
count         10800.000000        10800.000000  10800.000000  10800.000000   
mean             87.115093           20.423148    195.080278     26.359722   
std              19.744375           12.165320     26.136732      3.820147   
min              48.000000            0.000000    150.000000     20.000000   
25%              72.000000           10.000000    173.000000     23.000000   
50%              85.000000           20.000000    196.000000     26.000000   
75%             100.000000           31.000000    217.000000     30.000000   
max             161.000000           45.000000    245.000000     34.000000   

                AGE  EXERCISEMINPERWEEK  
count  10800.000000        10800.000000  
mean      49.965185          119.729537  
std       13.079281           71.147060  
min       28.000000            0.000000  
25%       39.000000           58.000000  
50%       50.000000          119.000000  
75%       61.000000          180.000000  
max       72.000000          250.000000

In [ ]:
#data preprocessing
#handle missing values
df.isnull().any()

AVGHEARTBEATSPERMIN    False
PALPITATIONSPERDAY     False
CHOLESTEROL            False
BMI                    False
HEARTFAILURE           False
AGE                    False
SEX                    False
FAMILYHISTORY          False
SMOKERLAST5YRS         False
EXERCISEMINPERWEEK     False
dtype: bool

In [ ]:
df.isnull().sum()

AVGHEARTBEATSPERMIN    0
PALPITATIONSPERDAY     0
CHOLESTEROL            0
BMI                    0
HEARTFAILURE           0
AGE                    0
SEX                    0
FAMILYHISTORY          0
SMOKERLAST5YRS         0
EXERCISEMINPERWEEK     0
dtype: int64

In [ ]:
df.isnull().any()

AVGHEARTBEATSPERMIN    False
PALPITATIONSPERDAY     False
CHOLESTEROL            False
BMI                    False
HEARTFAILURE           False
AGE                    False
SEX                    False
FAMILYHISTORY          False
SMOKERLAST5YRS         False
EXERCISEMINPERWEEK     False
dtype: bool

In [ ]:
#convert textual columns to numerical---- Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['HEARTFAILURE']= le.fit_transform(df['HEARTFAILURE'])# YES, NO
df['SEX']= le.fit_transform(df['SEX'])# Female, Male
df['FAMILYHISTORY']= le.fit_transform(df['FAMILYHISTORY'])# YES, NO
df['SMOKERLAST5YRS']= le.fit_transform(df['SMOKERLAST5YRS'])#yes,no


In [ ]:
df.head()

AVGHEARTBEATSPERMIN  PALPITATIONSPERDAY  CHOLESTEROL  BMI  HEARTFAILURE  \
0                   93                  22          163   25             0   
1                  108                  22          181   24             0   
2                   86                   0          239   20             0   
3                   80                  36          164   31             1   
4                   66                  36          185   23             0   

   AGE  SEX  FAMILYHISTORY  SMOKERLAST5YRS  EXERCISEMINPERWEEK  
0   49    0              0               0                 110  
1   32    0              0               0                 192  
2   60    0              0               0                 121  
3   45    0              1               0                 141  
4   39    0              0               0                  63

In [ ]:
#split into dependent and independent variables
x= df.drop(columns=['CHOLESTEROL','HEARTFAILURE']).values

In [ ]:
x

array([[ 93,  22,  25, ...,   0,   0, 110],
       [108,  22,  24, ...,   0,   0, 192],
       [ 86,   0,  20, ...,   0,   0, 121],
       ...,
       [103,   6,  20, ...,   0,   0, 205],
       [ 99,  30,  27, ...,   0,   0, 211],
       [ 50,  31,  26, ...,   0,   0,  54]])

In [ ]:
x.shape

(10800, 8)

In [ ]:
y= df['HEARTFAILURE'].values
y

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y.shape

(10800,)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
one= OneHotEncoder()
z= one.fit_transform(x[:,10:11]).toarray()
z

ValueError: ignored

In [ ]:
x = np.delete(x,10,axis=1)
x =np.concatenate((z,x),axis=1)

In [ ]:
x.shape

(614, 13)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train.shape

(8640, 8)

In [ ]:
x_test.shape

(2160, 8)

In [ ]:
x

array([[ 93,  22,  25, ...,   0,   0, 110],
       [108,  22,  24, ...,   0,   0, 192],
       [ 86,   0,  20, ...,   0,   0, 121],
       ...,
       [103,   6,  20, ...,   0,   0, 205],
       [ 99,  30,  27, ...,   0,   0, 211],
       [ 50,  31,  26, ...,   0,   0,  54]])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train= sc.fit_transform(x_train)
x_test= sc.fit_transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
log= LogisticRegression()
log.fit(x_train,y_train)

LogisticRegression()

In [ ]:
logpred= log.predict(x_test)
logpred

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
y_test

array([1, 0, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score
logacc= accuracy_score(y_test,logpred)
logacc

0.8712962962962963

In [ ]:
from sklearn.metrics import confusion_matrix
logcm= confusion_matrix(logpred,y_test)

In [ ]:
logcm

array([[1759,  224],
       [  54,  123]])

In [ ]:
#model building with decision tree classifier
from sklearn.tree import DecisionTreeClassifier
dtc= DecisionTreeClassifier(criterion='entropy')
dtc.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [ ]:
dtcpred= dtc.predict(x_test)
dtcpred

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
dtcacc= accuracy_score(dtcpred,y_test)
dtcacc

0.8087962962962963

In [ ]:
dtccm= confusion_matrix(dtcpred,y_test)

In [ ]:
dtccm

array([[1585,  185],
       [ 228,  162]])

In [ ]:
#model building using random forest classifier
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(criterion='entropy')
rfc.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy')

In [ ]:
rfc_pred= rfc.predict(x_test)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')